### ISSUE TITLE
Plugin does not initialise Version 57.0.2987.133 (64-bit)

### ISSUE THREAD

**Issue by peatriks** [christianblais/shopify-translator#3]
Hi there,
thanks for putting this out there, we will contribute with German translations.

When I pick a language while in the admin via the plugin, nothing happens. It does not seem like a request is even started (however, I have no idea how to debug plugins).

Best
Patrick

**Comment by christianblais** [comment]
And if you try refreshing the page, is it translated?

**Comment by peatriks** [comment]
That's embarrassing, this was the trick :D
